### ISSUE TITLE
Initial project setup

### ISSUE THREAD

**Issue by hanapotski** [webdevangelie/inventoryapp#2]
- [x] from the root folder, initialize a git repo

### Frontend
- [x] from the root folder, create a folder for `client`
- [x] initialize a react app

### Backend
- [x] from the root folder, create a folder for `server`
- [x] initialize a node app

### Push your changes to github
- [x] make sure to ignore the `node_modules` before pushing
- [x] commit and push changes

**Comment by webdevangelie** [comment]
I push my code to GitHub but they are not showing for some reason?
